### ISSUE TITLE
msgBuf cannot be shared, as ConsumeClaim is being called for diff topics partitions

### ISSUE THREAD

**Issue by alok87** [sceneryback/kafka-best-practices#3]
https://github.com/sceneryback/kafka-best-practices/blob/c72c1566d240f3641f84d3fa3e74421783f32989/consumer/consume_multi_batch_handler.go#L29 

since msgBuf is shared. It is going to get data from Topic A and Topic B both
Instead msgBuf should be created separately for each ConsumeClaim

**Comment by sceneryback** [comment]
Hi alok87, yes, I pass messages of different topics into msgBuf, but since this struct contains the original ```*sarama.ConsumerMessage```, you can always distribute data of different topics in your handler code of msgBuf like:
```
for msg := range msgBuf {
    switch msg.Message.Topic {
       case "A":
          xxx
       case "B":
          yyy
    }
}
```
